"""github_oauth_demo_quota

Revision ID: 7468afc03983
Revises: a1c3f7e92b04
Create Date: 2026-05-27 19:02:17.417315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7468afc03983'
down_revision: Union[str, None] = 'a1c3f7e92b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('demo_ai_calls_used', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['github_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'demo_ai_calls_used')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
