"""add cascade delete on user foreign keys

Revision ID: c28267b1453c
Revises: eac66091c453
Create Date: 2026-05-28 15:48:31.836757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28267b1453c'
down_revision: Union[str, None] = 'eac66091c453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('body_measurements_user_id_fkey', 'body_measurements', type_='foreignkey')
    op.create_foreign_key(None, 'body_measurements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exercise_logs_user_id_fkey', 'exercise_logs', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('food_logs_user_id_fkey', 'food_logs', type_='foreignkey')
    op.create_foreign_key(None, 'food_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('meal_plan_items_meal_plan_id_fkey', 'meal_plan_items', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plan_items', 'meal_plans', ['meal_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('meal_plans_user_id_fkey', 'meal_plans', type_='foreignkey')
    op.create_foreign_key(None, 'meal_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.create_foreign_key('meal_plans_user_id_fkey', 'meal_plans', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'meal_plan_items', type_='foreignkey')
    op.create_foreign_key('meal_plan_items_meal_plan_id_fkey', 'meal_plan_items', 'meal_plans', ['meal_plan_id'], ['id'])
    op.drop_constraint(None, 'food_logs', type_='foreignkey')
    op.create_foreign_key('food_logs_user_id_fkey', 'food_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'exercise_logs', type_='foreignkey')
    op.create_foreign_key('exercise_logs_user_id_fkey', 'exercise_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'body_measurements', type_='foreignkey')
    op.create_foreign_key('body_measurements_user_id_fkey', 'body_measurements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
