"""add_registered_via

Revision ID: eac66091c453
Revises: 7468afc03983
Create Date: 2026-05-27 20:30:11.113443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac66091c453'
down_revision: Union[str, None] = '7468afc03983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_via', sa.Enum('email', 'github', name='registeredvia', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_via')
    # ### end Alembic commands ###
