export const ICON_BG = '/nomnom-icon-bg.png'
export const ICON_NO_PADDING = '/nomnom-icon-no_padding.png'
export const ICON_NO_BG = '/nomnom-icon-no_bg.png'
export const SMALL_ICON_BG = '/nomnom-icon-bg_small.png'
export const SMALL_ICON_NO_PADDING = '/nomnom-icon-no_padding_small.png'
export const SMALL_ICON_NO_BG = '/nomnom-icon-no_bg_small.png'
// export const ICON_NO_BG_ACTIVE = '/nomnom-icon-no_bg_active.png'
